### PR TITLE
update to RC3, new router

### PR DESCRIPTION
**Pull request by Tallyb**
update to RC4. Removed @requireUser as this is a path thing and not a component thing.

### CODE REVIEW

**Comment by Urigo** [comment]
thanks you!!
I'm in France with a really bad internet so publishing to Atmosphere doesn't work...
we you send me an email and I'll give you publishing credentials?

**Comment by Tallyb** [comment]
@urigo
Why atmosphere? Should be on npm, no?
I think you have my Gmail.

**Comment by Urigo** [comment]
ohh that's right..

but when trying to clone from scratch, running `npm install` then `typings install` than `npm publish` I get this error:
urigoldshtein$ npm publish

> angular2-meteor-accounts-ui@0.6.0 prepublish /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
> npm run build
> 
> angular2-meteor-accounts-ui@0.6.0 build /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
> npm run build:html && npm run build:styles && npm run build:js
> 
> angular2-meteor-accounts-ui@0.6.0 build:html /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
> gulp pages

(node:4737) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[15:54:50] Using gulpfile ~/Code/angular2-meteor-accounts-ui/gulpfile.js
[15:54:50] Starting 'pages'...
[15:54:50] Finished 'pages' after 29 ms

> angular2-meteor-accounts-ui@0.6.0 build:styles /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
> gulp less && gulp scss

(node:4740) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[15:54:51] Using gulpfile ~/Code/angular2-meteor-accounts-ui/gulpfile.js
[15:54:51] Starting 'less'...
[15:54:51] Finished 'less' after 74 ms
(node:4741) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[15:54:51] Using gulpfile ~/Code/angular2-meteor-accounts-ui/gulpfile.js
[15:54:51] Starting 'scss'...
[15:54:51] Finished 'scss' after 10 ms

> angular2-meteor-accounts-ui@0.6.0 build:js /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
> tsc

node_modules/@angular/common/src/directives/ng_class.d.ts(81,35): error TS2304: Cannot find name 'Set'.
node_modules/@angular/common/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/common/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/common/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/common/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(41,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(79,88): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(137,42): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(196,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(115,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(115,165): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/compiler.d.ts(13,59): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/component_resolver.d.ts(9,58): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/component_resolver.d.ts(13,49): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(61,148): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(102,144): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(107,139): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,135): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18,53): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(26,53): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router/src/router.d.ts(188,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router/src/router.d.ts(204,59): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.
src/login-buttons.ts(12,8): error TS2307: Cannot find module 'meteor/accounts-base'.
src/login-buttons.ts(16,8): error TS2307: Cannot find module 'meteor/tracker'.
src/login-buttons.ts(20,8): error TS2307: Cannot find module 'meteor/meteor'.
src/login-buttons.ts(33,32): error TS2304: Cannot find name 'module'.
src/login-buttons.ts(156,12): error TS2304: Cannot find name '_'.
src/annotations.ts(16,8): error TS2307: Cannot find module 'meteor/meteor'.
src/annotations.ts(57,5): error TS2335: 'super' can only be referenced in a derived class.
src/annotations.ts(57,16): error TS2339: Property 'canProceed' does not exist on type 'RequireUserAnnotation'.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:js"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-meteor-accounts-ui@0.6.0 build:js: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-meteor-accounts-ui@0.6.0 build:js script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-meteor-accounts-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-meteor-accounts-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-meteor-accounts-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/urigoldshtein/Code/angular2-meteor-accounts-ui/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-meteor-accounts-ui@0.6.0 build: `npm run build:html && npm run build:styles && npm run build:js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-meteor-accounts-ui@0.6.0 build script 'npm run build:html && npm run build:styles && npm run build:js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-meteor-accounts-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:html && npm run build:styles && npm run build:js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-meteor-accounts-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-meteor-accounts-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/urigoldshtein/Code/angular2-meteor-accounts-ui/npm-debug.log

npm ERR! addLocal Could not install /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-meteor-accounts-ui@0.6.0 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-meteor-accounts-ui@0.6.0 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-meteor-accounts-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-meteor-accounts-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-meteor-accounts-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/urigoldshtein/Code/angular2-meteor-accounts-ui/npm-debug.log
Dotans-MacBook-Pro:angular2-meteor-accounts-ui urigoldshtein$ 

and this is the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/urigoldshtein/Code/angular2-meteor-accounts-ui',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/urigoldshtein/.npm/angular2-meteor-accounts-ui/0.6.0/package.tgz not in flight; packing
9 verbose correctMkdir /Users/urigoldshtein/.npm correctMkdir not in flight; initializing
10 info lifecycle angular2-meteor-accounts-ui@0.6.0~prepublish: angular2-meteor-accounts-ui@0.6.0
11 verbose lifecycle angular2-meteor-accounts-ui@0.6.0~prepublish: unsafe-perm in lifecycle true
12 verbose lifecycle angular2-meteor-accounts-ui@0.6.0~prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/urigoldshtein/Code/angular2-meteor-accounts-ui/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
13 verbose lifecycle angular2-meteor-accounts-ui@0.6.0~prepublish: CWD: /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
14 silly lifecycle angular2-meteor-accounts-ui@0.6.0~prepublish: Args: [ '-c', 'npm run build' ]
15 silly lifecycle angular2-meteor-accounts-ui@0.6.0~prepublish: Returned: code: 1  signal: null
16 info lifecycle angular2-meteor-accounts-ui@0.6.0~prepublish: Failed to exec prepublish script
17 error addLocal Could not install /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
18 verbose stack Error: angular2-meteor-accounts-ui@0.6.0 prepublish: `npm run build`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:852:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
19 verbose pkgid angular2-meteor-accounts-ui@0.6.0
20 verbose cwd /Users/urigoldshtein/Code/angular2-meteor-accounts-ui
21 error Darwin 15.5.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
23 error node v6.3.0
24 error npm  v3.10.3
25 error code ELIFECYCLE
26 error angular2-meteor-accounts-ui@0.6.0 prepublish: `npm run build`
26 error Exit status 1
27 error Failed at the angular2-meteor-accounts-ui@0.6.0 prepublish script 'npm run build'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular2-meteor-accounts-ui package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     npm run build
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular2-meteor-accounts-ui
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular2-meteor-accounts-ui
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by mariohmol** [comment]
When running using the angular2-meteor-accounts-ui@head i have this error:

```
modules.js?hash=581afeb…:118671 Uncaught ReferenceError: _super is not defined

RequireUserAnnotation @ modules.js?hash=581afeb…:118671
DecoratorFactory @ decorators.js:179
(anonymous function) @ brigadas-details.ts:25
meteorInstall.client.imports.brigadas.brigadas-details.ts @ brigadas-details.ts:63
fileEvaluate @ install.js:153require @ install.js:82
meteorInstall.client.app.js @ app.js:17
fileEvaluate @ install.js:153
require @ install.js:82(anonymous function) @ usuarios.ts:3
```

```
var RequireUserAnnotation = (function () {                                                                             // 44
    function RequireUserAnnotation() {                                                                                 // 45
        _super.call(this, this.canProceed.bind(this));                                                                 // 46
    }  
```

**Comment by Tallyb** [comment]
@urigo I made a new or for fixes (I had a problem with the push of this pr)

**Comment by mariohmol** [comment]
Is this related with #22  ? I did some comments there!

**Pull request merged**
