### PR TITLE
master

### PR DESCRIPTION
**Pull request by Tallyb**
Fixes - update to RC3

### CODE REVIEW

**Comment by mariohmol** [comment]
Hi there!

Using your branch  i'm having this error

`Uncaught TypeError: angular2_meteor_accounts_ui_1.RequireUser is not a function`

```
@RequireUser()
export class BrigadasDetails {
```

**Comment by Tallyb** [comment]
@mariohmol I removed the @requireUser annotation. The reason is that with new new new router, routes are standalone and no longer related to a component, hence it make no sense to annotate it. [Other opinions are welcom]
I will create a new PR to have a router guard that can be used on the canActivate on route.

**Comment by mariohmol** [comment]
Right... I took the required user .. but when i use  `@CanActivate(checkPermissions)` from `import { ActivatedRoute, ROUTER_DIRECTIVES, CanActivate, ComponentInstruction } from '@angular/router';` i'm getting the error:

`Uncaught TypeError: router_1.CanActivate is not a function`  as i'm using angular/route , shouldnt it work? or this changed as well?

**Comment by Tallyb** [comment]
Are you using the new router (v3)? I do not think this is related to meteor-angular2-accounts-ui

**Comment by mariohmol** [comment]
I'm following the tutorial.. and trying to make an app using angular-material

http://www.angular-meteor.com/tutorials/socially/angular2/user-accounts-authentication-and-permissions

Here we have `CanActivate` and `RequireUser` , for now we know that requireduser will be deprecated.. and i dont know about canactive..  so i would like to open a issue in angular-meteor to update the tutorial considering those changes

**Comment by Tallyb** [comment]
I am trying to create an end version of  tutorial with RC4, new forms and new router.... (and angular-material)
This is where I have encountered the accounts ui issue. 
Still under construction, as I have limited time.

**Comment by mariohmol** [comment]
I can help if u want, if i have the repo for this tutorial i can make some PR considering the changes. 

Just let me know if i can help ..

**Comment by cgalvarez** [comment]
Hi, @Tallyb. @angular/deprecated-router [exports](https://github.com/angular/angular/blob/master/modules/%40angular/router-deprecated/router.ts#L24)  the `CanActivate` class, but @angular/router [doesn't](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L392).
I'm using the latest released version (3.0.0-beta.2), but the problem is still there, throwing the error `src/annotations.ts: error TS2304: Cannot find name 'CanActivate'`.

Still fails if importing the `CanActivate` interface with `import {CanActivate} from "@angular/router/src/interfaces";`. TypeScript throws the error `super can only be used from derived class` because of implementing the interface instead of extending the (non-exported) class.

Besides all of this, TypeScript throws me the error `src/login-buttons.ts: error TS2339: Property 'oauth' does not exist on type 'typeof Accounts`, which I don't know how to fix.

Like @mariohmol said, let me know if I can help.

**Comment by mariohmol** [comment]
seems that all those erros for typescript is something that happens in every project.. and they are fixing..

about the changes in route.. angular2-meteor and angular2 are changing a lot.. until we get a final release.. will be this mess =(

**Comment by Tallyb** [comment]
@mariohmol @cgalvarez 
I get typescript errors on 
`let services = Package['accounts-oauth'] ? Accounts.oauth.serviceNames() : [];`
The problem is that there is no oauth method on accounts in the typescript. Anyone familiar?

**Comment by Tallyb** [comment]
@cgalvarez - CanActivate is exported as I can see in my IDE, as well as in the angualr router documentation (app/auth.guard.ts)
image

**Comment by mariohmol** [comment]
i saw a thread in route3 saying that canactive will no longer exist

**Comment by Tallyb** [comment]
@mariohmol  can you link to it? will be interesting...

**Comment by davidbonachera** [comment]
Well for me it's working well, i just use injectUser sometimes and i use canActivate only in a route definition example : 

``` javascript
{
        path: 'member',
        component: Member,
        canActivate: [AuthGuard],
        children: [
            { path: '', component: Home, canActivate: [AuthGuard]},
            { path: 'account', component: Account, canActivate: [AuthGuard]},
            { path: 'survey', component: Survey, canActivate: [AuthGuard]},
        ]
    },
```

But as far as i know, you can use it in a regular way : 
https://angular.io/docs/ts/latest/guide/router.html#!#can-activate-guard

**Comment by mariohmol** [comment]
See this discussion.. is not what i saw before.. but i guess that points for what i understood

https://github.com/angular/angular/issues/6611#issuecomment-193221111
https://github.com/angular/angular/issues/4015#issuecomment-220033358

**Comment by mariohmol** [comment]
you are right.. canactivate is in rc4 =) https://github.com/angular/angular/commit/f2f1ec0

**Comment by dohomi** [comment]
Here is a nice article about guards: http://blog.thoughtram.io/angular/2016/07/18/guards-in-angular-2.html

**Comment by dotansimha** [comment]
Hi @Tallyb ,
Please resolve the conflicts so I can merge it. 
I think that the best approach is to wait until Angular 2 will release a stable version of the new router, because we also need to update the usage of this package and the new router in the angular2-meteor socially tutorial. 

Also, can you please provide a usage example for the new API of the package? 

@barbatus, @Urigo  - what do you think?

Thanks!!

**Comment by barbatus** [comment]
@dotansimha I think `InjectUser` has anything to do with the router. And for  the `RequireUserAnnotation`, we'll need to create `RequireUserGuard` instead which will be almost the same.

**Comment by dotansimha** [comment]
Hi @Tallyb , I manually merged it. thanks!

**Pull request merged**
